<!--- 
	configuration file.
	this file is automatically generated
	
 --->
 
<cfset activescan = StructNew()>
<cfset activescan["null"] = 0>
<cfset activescan['c:\inetpub\wwwroot\uploads\'] = 5030>
<cfset activescan['c:\inetpub\wwwroot\uploads\'] = 5030>
